### ISSUE TITLE
ImportError: cannot import name 'range' from 'openpyxl.compat'

### ISSUE THREAD

**Issue by jgamblin** [Zocdoc/ZocSec.SecurityAsCode.GitHub#4]
While trying to run the inventory tool I get this error on MacOS: 

```$ sudo python3 kyro.py
Traceback (most recent call last):
  File "kyro.py", line 19, in <module>
    from openpyxl.compat import range
ImportError: cannot import name 'range' from 'openpyxl.compat' (/usr/local/lib/python3.7/site-packages/openpyxl/compat/__init__.py)```

**Comment by garymalaysia** [comment]
Thanks for testing it out! I have created a PR [here](https://github.com/garymalaysia/ZocSec.SecurityAsCode.GitHub/tree/master/GitHub_Inventory_Tool) for this fix. I hope this fix can be merged soon by @jay-ball-zocdoc

**Comment by jay-ball-zocdoc** [comment]
Should be closed per PR#4

**Comment by ruby621** [comment]
This issue is not resolved.  I have Python 3.7.3 -32 with all the pip packages at latest revision and still seeing this issue:
 from openpyxl.compat import range
E   ImportError: cannot import name 'range' from 'openpyxl.compat' (c:\program files (x86)\python37-32\lib\site-packages\openpyxl\compat\__init__.py)

 
NOTE: I am seeing it even with pytest 5.3.5  Please help and suggest quick solution.

FYI, i also have 3.8.2rc2 build that i have separate environment switch for. I am also seeing the same issue on Python V3.8.2Rc2:
from openpyxl.compat import range
E   ImportError: cannot import name 'range' from 'openpyxl.compat' (c:\program files (x86)\python38-32\lib\site-packages\openpyxl\compat\__init__.py)

**Comment by garymalaysia** [comment]
This line of code ```from openpyxl.compat import range``` does not exist in master branch. Can you point to where did you see it.

**Comment by ruby621** [comment]
Sorry, i am running a test framework for the first time at my new gig.  This is being called from one of the Classes like so:


from openpyxl.compat import range
import os
from selenium import webdriver
from openpyxl.reader.excel import load_workbook
from openpyxl.workbook.workbook import Workbook

class ExcelMainClass():

its not part of the python release. It seems this code may be outdated.  Sorry, for false alarms.
